# Generated by Django 5.2.4 on 2025-07-25 12:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Saga',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('saga_type', models.CharField(db_index=True, max_length=100)),
                ('related_resource_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='in_progress', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SagaStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('saga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='messaging.saga')),
            ],
            options={
                'unique_together': {('saga', 'service_name')},
            },
        ),
    ]
