# Generated by Django 5.2.4 on 2025-07-22 20:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelDefinition',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(db_index=True, max_length=100)),
                ('capabilities', models.JSONField(default=list)),
                ('config_schema', models.JSONField(default=dict)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('config_values', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configurations', to='aimodels.modeldefinition')),
            ],
            options={
                'verbose_name': 'Model Configuration',
                'verbose_name_plural': 'Model Configurations',
                'ordering': ['-created_at'],
                'unique_together': {('owner_id', 'name')},
            },
        ),
    ]
