# Generated by Django 5.2.4 on 2025-07-22 21:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimodels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_system_model', models.BooleanField(db_index=True, default=False, help_text='True if this is a global model template managed by an admin.')),
                ('owner_id', models.UUIDField(blank=True, db_index=True, help_text='The user who owns this configuration. NULL for system models.', null=True)),
                ('name', models.CharField(help_text="User-friendly name (e.g., 'My Personal GPT-4o' or 'System Llama 3').", max_length=255)),
                ('provider', models.CharField(db_index=True, help_text="Provider identifier (e.g., 'openai', 'ollama', 'anthropic').", max_length=100)),
                ('configuration', models.JSONField(default=dict, help_text='For system models: the JSON schema. For user models: the encrypted config values.')),
                ('capabilities', models.JSONField(default=list, help_text="List of capabilities (e.g., ['text', 'vision', 'tool_use']).")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Model Configuration',
                'ordering': ['-is_system_model', 'provider', 'name'],
                'constraints': [models.UniqueConstraint(fields=('owner_id', 'name'), name='unique_user_model_name')],
            },
        ),
        migrations.DeleteModel(
            name='ModelConfiguration',
        ),
        migrations.DeleteModel(
            name='ModelDefinition',
        ),
    ]
