# Generated by Django 5.2.4 on 2025-07-23 19:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_id', models.UUIDField(db_index=True, help_text='The Project this Node belongs to.')),
                ('owner_id', models.IntegerField(db_index=True, help_text='The User who owns this Node.')),
                ('name', models.CharField(help_text="The user-defined name for this Node (e.g., 'My Research Agent').", max_length=255)),
                ('configuration', models.JSONField(default=dict, help_text="The complete configuration blueprint for this node's behavior.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Node',
                'verbose_name_plural': 'Nodes',
                'ordering': ['-created_at'],
            },
        ),
    ]
