# Generated by Django 5.2.4 on 2025-07-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='owner_id',
            field=models.UUIDField(db_index=True, help_text='The UUID of the user who owns this Node. Corresponds to the User UUID in the Auth service JWT.'),
        ),
    ]
