# Generated by Django 5.2.4 on 2025-08-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_alter_node_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('altered', 'Altered'), ('inactive', 'Inactive')], db_index=True, default='active', help_text='The current status of the node (e.g., active, altered, inactive).', max_length=20),
        ),
    ]
