# Generated by Django 5.2.4 on 2025-08-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0003_node_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('altered', 'Altered'), ('inactive', 'Inactive'), ('draft', 'Draft')], db_index=True, default='draft', help_text='The current status of the node (e.g., active, altered, inactive).', max_length=20),
        ),
    ]
