# Generated by Django 5.2.5 on 2025-08-30 19:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryBucket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('owner_id', models.UUIDField(db_index=True, help_text='The user who owns this bucket.')),
                ('project_id', models.UUIDField(db_index=True, help_text='The project this bucket belongs to.')),
                ('memory_type', models.CharField(default='conversation_buffer_window', max_length=100)),
                ('config', models.JSONField(default=dict, help_text="Type-specific config, e.g., {'k': 10}")),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.JSONField()),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='memory.memorybucket')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
