# Generated by Django 5.2.5 on 2025-08-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorybucket',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
