# Generated by Django 5.2.5 on 2025-08-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0002_alter_memorybucket_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorybucket',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
