# Generated by Django 5.2.4 on 2025-07-21 18:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier for the project.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The user-defined name of the project.', max_length=255)),
                ('owner_id', models.IntegerField(db_index=True, help_text='The ID of the user who owns this project. This corresponds to the User PK in the Auth service.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the project was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the project was last updated.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Optional flexible metadata for the project (e.g., labels, settings).')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
