# Generated by Django 5.2.4 on 2025-07-21 20:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner_id',
            field=models.UUIDField(db_index=True, help_text='The UUID of the user who owns this project. Corresponds to the User ID in the Auth service.'),
        ),
    ]
