# Generated by Django 5.2.4 on 2025-07-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_id_alter_project_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending_deletion', 'Pending Deletion')], db_index=True, default='active', help_text='The current status of the project (e.g., active, pending deletion).', max_length=20),
        ),
    ]
