# Generated by Django 5.2.4 on 2025-08-02 15:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Unique, programmatic name, e.g., 'get_current_weather'.", max_length=255)),
                ('is_system_tool', models.BooleanField(db_index=True, default=False)),
                ('owner_id', models.UUIDField(blank=True, db_index=True, help_text='NULL for system tools.', null=True)),
                ('tool_type', models.CharField(choices=[('standard', 'Standard'), ('mcp', 'Model Context Protocol')], default='standard', max_length=20)),
                ('definition', models.JSONField(help_text="The tool's complete definition, including its schema and execution details.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_system_tool', 'name'],
                'unique_together': {('owner_id', 'name')},
            },
        ),
    ]
