# Generated by Django 5.2.6 on 2025-09-03 18:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_id', models.UUIDField(db_index=True)),
                ('project_id', models.UUIDField(db_index=True)),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField()),
                ('storage_path', models.CharField(help_text='Path/key to the raw file in object storage.', max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
